config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cv', to: 'pages#cv'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :job_offers do
    resources :cv_generations, only: [:new, :create]
  end

  resources :cv_generations, except: [:new, :create] do
    resources :cvs, only: :create
  end

  resources :profiles, only: [:new, :show, :edit, :update, :create]
  resources :cvs, only: :show
  get "user/dashboard", to: "pages#dashboard"
  resources :skills, only: [:create, :update, :destroy]
  resources :experiences, only: [:create, :update, :destroy]
  resources :degrees, only: [:create, :update, :destroy]
  resources :languages, only: [:create, :update, :destroy]

    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  # get 'cv/download', to: 'cv#download', as: 'download_cv'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="navbar">
  <a href="/" class="brand-title">CuryAi</a>
  <nav>
    <% if user_signed_in? %>
    <div class="dropdown">
      <%= image_tag("lucas-et-son-chien.png", alt: "Profile", class: "profile-icon") %>
      <div class="dropdown-content">
        <%= link_to 'Dashboard', user_dashboard_path, class: 'dropdown-link' %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-link' %>
      </div>
    </div>
    <% else %>
      <%= link_to 'Log In', new_user_session_path, class: 'login-button' %>
      <span class="button-space"></span>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'signup-button' %>
    <% end %>
  </nav>
</header>