config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cv', to: 'pages#cv'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :job_offers do
    resources :cv_generations, only: [:new, :create]
  end

  resources :cv_generations, except: [:new, :create] do
    resources :cvs, only: :create
  end

  resources :profiles, only: [:new, :show, :edit, :update, :create]
  resources :cvs, only: :show
  get "user/dashboard", to: "pages#dashboard"
  resources :skills, only: [:create, :update, :destroy]
  resources :experiences, only: [:create, :update, :destroy]
  resources :degrees, only: [:create, :update, :destroy]
  resources :languages, only: [:create, :update, :destroy]

    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  # get 'cv/download', to: 'cv#download', as: 'download_cv'
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :profile
  validates :title, presence: true
  validates :level, presence: true
  validates :level, inclusion: { in: ["Bac", "Bac +2", "Bac +3", "Bac +5", "Doctora"] }
  validates :field, presence: true
  validates :school, presence: true
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController

  before_action :set_degree, only: [:destroy]

  def create
    @profile = current_user.profile
    @degree = Degree.new(params_degree)
    @degree.profile_id = @profile.id
    @degree.save

    respond_to do |format|
      format.html { redirect_to profile_path }
      format.json
    end
  end

  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to profile_path, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_degree
    @degree = Degree.find(params[:id])
  end
  
  def params_degree
    params.require(:degree).permit(:title, :level, :field, :school)
  end
end

app/views/degrees/_degree.html.erb
<div class="step2-infos-details">
 <div class="accordion" id="accordionDegrees">
    <% if @profile.degrees.present? %>
      <% @profile.degrees.each_with_index do |degree, index| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading<%= index %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
              <%= degree.title %>
            </button>
          </h2>
          <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionDegrees">
            <div class="accordion-body">
              <strong>Your Degree level</strong> <%= degree.level %><br>
              <strong>Your Degree Field</strong> <%= degree.field %><br>
              <strong>Your Degree's school</strong> <%= degree.school %><br>
               <!-- Button trigger modal -->
              <div class="delete-button-container">
                <button type="button" data-controller="delete" data-action="click->delete#delete" data-delete-url-value="<%= degree_path(degree) %>" class="icon-button-delete">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div>No degrees</div>
    <% end %>
  </div>
</div>