config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cv', to: 'pages#cv'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :job_offers do
    resources :cv_generations, only: [:new, :create]
  end

  resources :cv_generations, except: [:new, :create] do
    resources :cvs, only: :create
  end

  resources :profiles, only: [:new, :show, :edit, :update, :create]
  resources :cvs, only: :show
  get "user/dashboard", to: "pages#dashboard"
  resources :skills, only: [:create, :update, :destroy]
  resources :experiences, only: [:create, :update, :destroy]
  resources :degrees, only: [:create, :update, :destroy]
  resources :languages, only: [:create, :update, :destroy]

    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  # get 'cv/download', to: 'cv#download', as: 'download_cv'
end

app/views/pages/cv.html.erb
<div class="body-cv">
    <div class="cv-container">
      <div class="left-column">
        <div class="portrait">
          <%= image_tag("image-pdf-cv-test.png", alt: "Profil picture of your CV") %>
        </div>
        <div class="section">
          <p>
            <i class="icon fab fa-linkedin text-darkblue"></i> Prénom NOM
          </p>
        </div>
        <div class="section">
          <h2>À PROPOS</h2>
          <p>
          Small description about my self my professionnal profile
          </p>

        </div>
        <div class="section">
          <h2>Skills</h2>
          <ul class="skills">
            <li><i class="icon fas fa-check-circle text-darkblue"></i> <strong>Skill</strong></li>
            <li><i class="icon fas fa-check-circle text-darkblue"></i> <strong>Another Skills</strong></li>
          </ul>
        </div>
        <div class="section">
          <h2>Languages</h2>
          <p>
            French, level
            <br>
            English, Level
          </p>
        </div>
        <div class="section">
          <h2>Hobbies</h2>
          <p>
            Video games, playing and developing
            <br>
            Music, listening and composition
            <br>
            Art
            <br>
            Sports
            <br>
            Informatic
          </p>
        </div>
      </div>
      <div class="right-column">
        <div class="header">
          <h1>Prénom <span class="text-blue text-uppercase">NOM</span></h1>
          <p>Poste de job offer</p>
          <ul class="infos">
            <li><i class="icon fas fa-at text-blue"></i> <a href="email">email</a></li>
            <li><i class="icon fas fa-phone text-blue"></i>numéro de téléphone</li>
            <li><i class="icon fas fa-map-marker-alt text-blue"></i> adresse</li>
          </ul>
        </div>
        <div class="content">
          <div class="section">
            <h2 class="text-blue">experiences</h2>
            <p>
              <strong>starting date <i class="fas fa-long-arrow-alt-right"></i> ending date</strong>
              <br>
              intitulé du poste <em>entreprise</em>
            </p>
            <ul class="experience-list">
              <%# first experience example %>
              <li>Website, e-shop, interface, and web application developments using Angular and Bootstrap</li>
              <li>Integration of Photoshop templates, Illustrator, Sketch, Figma</li>
              <li>Animations CSS / JS</li>
              <li>Responsive design</li>
              <li>UI / UX Design</li>
              <li>Projets on npm and Webpack</li>
              <li>Collaboration with otehr graphic studios </li>
              <li>Performance optimization</li>
              <li>Development of reusable templates and modules</li>
              <li>Team projects, daily use of SVN, Git, and Github</li>
            </ul>
          </div>
          <div class="section">
            <p>
              <strong>2021</strong>
              <br>
              Freelance activity
            </p>
            <ul class="experience-list">
              <%# second experience example %>
              <li>Freelance Front-end Developer</li>
              <li>Unity Developer / Sound Designer</li>
            </ul>
          </div>
          <div class="section">
            <h2>Education <br><span class="text-blue">& formations</span></h2>
            <p>
              <strong>starting date <i class="fas fa-long-arrow-alt-right"></i> ending date</strong>
              <br>
              <em>Bachelor's degree in Business Informatics</em> Graduate, Saint Laurent Institute
            </p>
            <p>
              <strong>2015</strong>
              <br>
              <em>Le Wagon - Web development</em>, Qualifying training as a Web Developer
            </p>
            <p>
              <strong>2013 <i class="fas fa-long-arrow-alt-right"></i> 2014</strong>
              <br>
              <em>Bachelor's degree in Humanities</em>, High school from Bordeaux
            </p>

          </div>
          <div class="section">
            <h2>Others <br><span class="text-blue">experiences</span></h2>
            <p>
              Driver's license B, own a car
              <br>
              Scout Leader for 6 years
              <br>
              Holiday Camp Animator Certificate
            </p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard" data-controller="dashboard">
  <aside class="dashboard-sidebar">
    <h2>Dashboard</h2>
    <ul>
      <li><a href="#profile"  data-action="click->dashboard#changeSection" data-target="profile"><i class="fa fa-user"></i>Profile</a></li>
      <li><a href="#experiences" data-action="click->dashboard#changeSection" data-target="experiences"><i class="fa fa-briefcase"></i>Experiences</a></li>
      <li><a href="#skills"  data-action="click->dashboard#changeSection" data-target="skills"><i class="fa fa-code"></i>Skills</a></li>
      <li><a href="#degrees"  data-action="click->dashboard#changeSection" data-target="degrees"><i class="fa fa-graduation-cap"></i>Degrees</a></li>
      <li><a href="#languages"  data-action="click->dashboard#changeSection" data-target="languages"><i class="fa fa-language"></i>Languages</a></li>
      <li><a href="#joboffer"  data-action="click->dashboard#changeSection" data-target="joboffer"><i class="fa fa-handshake"></i>Job Offer</a></li>
      <li><a href="#cvs"  data-action="click->dashboard#changeSection" data-target="cvs"><i class="fa fa-file-alt"></i>  Generated Resumes</a></li>
    </ul>
    <div class="add-cv-button">
      <a href="your-link-to-add-cv" class="add-cv-link">
        <i class="fa fa-plus" aria-hidden="true"></i>
        Add new CV
      </a>
    </div>
  </aside>
  <main class="dashboard-content">
    <!-- Profile Section -->
    <section id="profile" class="dashboard-section" data-dashboard-target="section">
      <div class="h2-dash">
        <h2>Contact informations</h2>
      </div>
      <!-- The rest of your profile content -->
      <% if @profile %>
        <div class="contact-infos">
          <h4>Contact informations</h4>
          <div class="contact-list">
            <p><strong>First name </strong><%= @profile.first_name %></p>
            <p><strong>Last name </strong><%= @profile.last_name %></p>
            <p><strong>Address </strong><%= @profile.address %></p>
            <p><strong>Age </strong><%= @profile.age %></p>
            <p><strong>Phone number </strong><%= @profile.phone_number %></p>
            <p><strong>@email </strong><%= @profile.email %></p>
            <p><strong>photo </strong><%= image_tag(@profile.photo, alt: "Description of the image", class: "photo-avatar-edit") %></p>
          </div>
        </div>
      </section>
      <!-- Experiences Section -->
      <section id="experiences" class="dashboard-section" data-dashboard-target="section">
        <div class="h2-dash">
          <h2>Professional experiences</h2>
        </div>
        <!-- The rest of your experiences content -->
        <div class="accordion" id="experienceAccordion">
          <% if @profile.experiences.present? %>
            <% @profile.experiences.each_with_index do |experience, index| %>
              <div class="accordion-item-dash">
                <h2 class="accordion-header-dash" id="heading-dash<%= index %>">
                  <button id="boutton-accordion-dash" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExperience<%= index %>" aria-expanded="false" aria-controls="collapseExperience<%= index %>">
                    <%= experience.title %>
                  </button>
                </h2>
                <div id="collapseExperience<%= index %>" class="accordion-collapse collapse" aria-labelledby="headingExperience<%= index %>" data-bs-parent="#experienceAccordion">
                  <div class="accordion-body-dashboard">
                    <div class="content-dash-accordion"><strong>Type</strong> <%= experience.experience_type %><br></div>
                    <div class="content-dash-accordion"><strong>Started</strong> <%= experience.starting_date %><br></div>
                    <div class="content-dash-accordion"><strong>Ended</strong> <%= experience.ending_date %><br></div>
                    <div class="content-dash-accordion"><strong>Description</strong> <%= experience.description %></div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="no-experience-message">No Experiences</div>
          <% end %>
        </div>
      </section>
      <!-- Skills Section -->
      <section id="skills" class="dashboard-section" data-dashboard-target="section">
        <div class="h2-dash">
          <h2>Skills</h2>
        </div>
        <!-- The rest of your skills content -->
        <div class="accordion" id="accordionExample">
          <% if @profile.skills.present? %>
            <% @profile.skills.each_with_index do |skill, index| %>
              <div class="accordion-item-dash">
                <h2 class="accordion-header-dash" id="heading-dash<%= index %>">
                  <button id="boutton-accordion-dash" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="false" aria-controls="collapse<%= index %>">
                    Skill number <%= index + 1 %>
                  </button>
                </h2>
                <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionExample">
                  <div class="accordion-body-dashboard">
                    <div class="content-dash-accordion"><strong>Your skill:</strong> <%= skill.title %><br>
                    </div>
                    <div class="content-dash-accordion"><strong>Your level:</strong> <%= skill.level %></div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div>No Skills</div>
          <% end %>
        </div>
      </section>
      <!-- Degrees Section -->
      <section id="degrees" class="dashboard-section" data-dashboard-target="section">
        <div class="h2-dash">
          <h2>Degrees</h2>
        </div>
        <!-- The rest of your degrees content -->
        <div class="accordion" id="accordionDegrees">
          <% if @profile.degrees.present? %>
            <% @profile.degrees.each_with_index do |degree, index| %>
              <div class="accordion-item-dash">
                <h2 class="accordion-header-dash" id="heading-dash<%= index %>">
                  <button id="boutton-accordion-dash" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                    Degree <%= index + 1 %>
                  </button>
                </h2>
                <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionDegrees">
                  <div class="accordion-body-dashboard">
                    <div class="content-dash-accordion"><strong>Your Degree name:</strong> <%= degree.title %><br>
                    </div>
                    <div class="content-dash-accordion"><strong>Your Degree level:</strong> <%= degree.level %><br>
                    </div>
                    <div class="content-dash-accordion"><strong>Your Degree Field:</strong> <%= degree.field %><br>
                    </div>
                    <div class="content-dash-accordion"><strong>Your Degree's school:</strong> <%= degree.school %><br>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div>No degrees</div>
          <% end %>
        </div>
      </section>
      <!-- Languages Section -->
      <section id="languages" class="dashboard-section" data-dashboard-target="section">
        <div class="h2-dash">
          <h2>Languages</h2>
        </div>
        <!-- The rest of your languages content -->
        <div class="step3-infos-language-details">
          <div class="accordion" id="languageAccordion">
            <% if @profile.languages.present? %>
              <% @profile.languages.each_with_index do |language, index| %>
                <div class="accordion-item-dash">
                  <h2 class="accordion-header-dash" id="heading-dash<%= index %>">
                    <button id="boutton-accordion-dash" class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLanguage<%= index %>" aria-expanded="true" aria-controls="collapseLanguage<%= index %>">
                      Language <%= index + 1 %>: <%= language.title %>
                    </button>
                  </h2>
                  <div id="collapseLanguage<%= index %>" class="accordion-collapse collapse" aria-labelledby="headingLanguage<%= index %>" data-bs-parent="#languageAccordion">
                    <div class="accordion-body-dashboard">
                      <div class="content-dash-accordion"><strong>Your level:</strong> <%= language.level %></div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div>No languages</div>
            <% end %>
          </div>
        </div>
      <% else %>
        <p>You have not completed your profile yet.</p>
        <%= link_to 'Complete Profile', new_profile_path %>
      <% end %>
    </section>
    <!-- Job Offer Section -->
    <section id="joboffer" class="dashboard-section" data-dashboard-target="section">
      <div class="h2-dash">
        <h2>Targeted Job Offer</h2>
      </div>
      <!-- The rest of your job offer content -->
      <% if @job_offers %>
        <div class="dash-joboffer">
          <% @job_offers.each do |job_offer| %>
            <div class="joboffer-list">
              <p><strong>Title: </strong><%= job_offer.title %></p>
              <p><strong>Description: </strong><%= job_offer.description %></p>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>You have not provided any job offer yet.</p>
        <%= link_to 'Complete Profile', new_profile_path %>
      <% end %>
    </section>
    <!-- Generated Resumes Section -->
    <section id="cvs" class="dashboard-section" data-dashboard-target="section">
      <div class="h2-dash">
        <h2>Your Generated Resumes</h2>
      </div>
      <!-- The rest of your resumes content -->
      <% if @cvs.present? %>
        <div class="dash-cvs">
          <h4>Your generated resumes</h4>
          <% @cvs.each do |cv| %>
            <div class="cvs-list">
              <p><strong>Title:</strong><%= cv.title %></p>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="h4-dash">
          <p>You have not generated any resumes yet.</p>
        </div>
      <% end %>
    </section>
  </main>
</div>

app/views/pages/home.html.erb
<section class="hero-section">
  <div class="waves-container">
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
      <defs>
        <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
      </defs>
      <g class="parallax">
        <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(88, 70, 251, 0.3)" />
        <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(88, 70, 251, 0.3)" />
        <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(88, 70, 251, 0.3)" />
        <use xlink:href="#gentle-wave" x="48" y="7" fill="rgba(88, 70, 251, 0.3)" />
      </g>
    </svg>
  </div>
  <div class="hero-content">
    <h1>Cury AI<br>
      generate CV</h1>
    <p>Discover a new way to generate resumes with artificial intelligence.</p>
    <% if @user.present? && @user.profile.present? %>
      <%= link_to 'Resume profile', profile_path(@user), class: 'cta-button' %>
    <% else %>
      <%= link_to 'Start generating your CV !', new_profile_path, class: 'cta-button' %>
    <% end %>
  </div>
</section>
<section class="service-features">
  <div class="feature">
    <p>Seamless, intuitive, engaging, and user experience.</p>
  </div>
  <div class="feature">
    <p>Ensure your resume stands out in competitive job market</p>
  </div>
  <div class="feature">
    <p>Effortlessly create professional resumes in minutes</p>
  </div>
  <div class="feature">
    <p>Ensure accuracy and consistency with our platform</p>
  </div>
</section>
<section class="resume-section">
  <div class="resume-content">
    <h2>Say goodbye to hours spent perfecting your resume</h2>
    <p>Let our artificial intelligence do the work for you.</p>
    <a href="#" class="generate-button">Generate now</a>
  </div>
  <div class="resume-image">
    <%= video_tag("video-home.mp4", autoplay: true, loop: true, muted: true, class: "resume-video") %>
  </div>
</section>
<section class="standout-section">
  <h2 class="standout-heading"><strong>Ready to stand out?</strong></h2>
  <div class="feature-cards">
    <div class="card">
      <div class="icon"> <%= image_tag("icone-home-resume.png")%></div>
      <h3>Tailored Resumes</h3>
      <p>Our AI adapts to your specific needs, generating a resume that perfectly aligns with your expertise.</p>
      <a href="#" class="learn-more-link">Learn more</a>
    </div>
    <div class="card">
      <div class="icon"><%= image_tag("icone-home-time.png")%></div>
      <h3>Save Precious Time</h3>
      <p>Create a resume in just a few clicks, without worrying about formatting or layout.</p>
      <a href="#" class="learn-more-link">Learn more</a>
    </div>
    <div class="card">
      <div class="icon"><%= image_tag("icone-home-recruiters.png")%></div>
      <h3>Impress Recruiters</h3>
      <p>Get a professional and compelling resume that sets you apart from the competition at first glance.</p>
      <a href="#" class="learn-more-link">Learn more</a>
    </div>
  </div>
  <a href="#" class="see-all-features-link">See all features</a>
</section>
<div id="homecarousel" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#homecarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#homecarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#homecarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="testimonial">
        <blockquote>"I'm absolutely thrilled with my experience with Cury AI. Their revolutionary platform has truly streamlined and sped up the process of creating my CV. Thanks to their cutting-edge artificial intelligence, I was able to generate a professional and impactful resume in just minutes."</blockquote>
        <div class="testimonial-footer">
          <div class="testimonial-image"> <%= image_tag("https://upload.wikimedia.org/wikipedia/commons/f/f4/Emmanuel_Macron_in_2019.jpg", alt: "Emmanuel Macron", class: "img-fluid") %></div>
          <div class="testimonial-name">Emmanuel Macron</div>
          <div class="testimonial-rating">★★★★★</div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="testimonial">
        <blockquote>"The service provided by Cury AI was exceptional. The intuitive interface and guidance helped me to build a resume that stands out in a crowded market. I'm deeply impressed by how easy and fast the whole process was."</blockquote>
        <div class="testimonial-footer">
          <div class="testimonial-image"> <%= image_tag("https://upload.wikimedia.org/wikipedia/commons/f/f4/USAFA_Hosts_Elon_Musk_%28Image_1_of_17%29_%28cropped%29.jpg", alt: "Elon Musk", class: "img-fluid") %></div>
          <div class="testimonial-name">Elon Musk</div>
          <div class="testimonial-rating">★★★★★</div>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev text-danger" type="button" data-bs-target="#homecarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#homecarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>