config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cv', to: 'pages#cv'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :job_offers do
    resources :cv_generations, only: [:new, :create]
  end

  resources :cv_generations, except: [:new, :create] do
    resources :cvs, only: :create
  end

  resources :profiles, only: [:new, :show, :edit, :update, :create]
  resources :cvs, only: :show
  get "user/dashboard", to: "pages#dashboard"
  resources :skills, only: [:create, :update, :destroy]
  resources :experiences, only: [:create, :update, :destroy]
  resources :degrees, only: [:create, :update, :destroy]
  resources :languages, only: [:create, :update, :destroy]

    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  # get 'cv/download', to: 'cv#download', as: 'download_cv'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
  has_many :cv_generations

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  def create
    @job_offer = JobOffer.new(job_offer_params)
    @job_offer.user = current_user
    if @job_offer.save
      redirect_to @job_offer, notice: 'Job offer was successfully added!'
    else
      render :new
    end
  end

  def show
    @job_offer = JobOffer.find(params[:id])
    @cv_generation = CvGeneration.new
    @cv_generation.job_offer_id = @job_offer.id
  end

  def edit
    @job_offer = JobOffer.find(params[:id])
  end

  def update
    @job_offer = JobOffer.find(params[:id])
    if @job_offer.update(job_offer_params)
      redirect_to @job_offer, notice: '✅ Job offer was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @job_offer = JobOffer.find(params[:id])
    @job_offer.destroy
    redirect_to new_job_offer_path, notice: 'Job offer has been deleted successfully!'
  end

  private

  def job_offer_params
    params.require(:job_offer).permit(:title, :description)
  end
end

app/views/job_offers/edit.html.erb
<div class="content-show-form">
  <span class="space-edit"></span>
  <div class="edit-job-offer-container">
    <h1>Edit Job Offer</h1>

    <%= simple_form_for @job_offer, html: { class: 'edit-job-offer-form' } do |f| %>
      <%= f.error_notification %>

      <div class="input">
        <%= f.input :title, input_html: { class: 'form-control' } %>
      </div>

      <div class="input">
        <%= f.input :description, input_html: { class: 'form-control' } %>
      </div>

      <div class="btn">
        <%= f.button :submit, "Update job offer !", class: 'btn-update-job-offer btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/job_offers/new.html.erb
<h1 class= "h1-new-joboffer">New Job Offer</h1>

app/views/job_offers/show.html.erb
<div class="content-show-form">
  <div class="container-show-job-offer">
  <div class="container-progress-bar">
      <div class="progress-bar">
            <div class="steps">
              <div class="step step-active"><span>01</span>
                    <p>Profile</p>
              </div>
              <div class="step step-active"><span>02</span>
                <p>Education</p>
              </div>
              <div class="step step-active"><span>03</span>
                <p>Skills</p>
              </div>
              <div class="step step-active"><span>04</span>
                <p>Work Experience</p>
              </div>
              <div class="step step-active"><span>05</span>
                <p>Job offer</p>
              </div>
              <div class="step"><span>06</span>
                <p>Generate CV</p>
              </div>
            </div>
        </div>
      </div>
    <div class="information-job-offer">
    <div class="complet-profile-banner">
          <h2>You will generate you CV based on that Offert :</h2>
          <p>Create your customized CV tailored to match the requirements and specifications outlined in the job offer.</p>
      </div>
      <div class="recap-info-job-offer">
        <p><strong>Title : </strong><%= @job_offer.title %></p>
        <p><strong>Description : </strong><%= @job_offer.description %></p>
      </div>
      <div class="boutton-container-job-offer">
      <%= link_to edit_job_offer_path(@job_offer), class: 'btn-edit' do %>
        <i class="fas fa-edit"></i> Edit this job offer
      <% end %>
      <%= link_to 'Generate', job_offer_cv_generations_path(@job_offer), class: 'btn-generate', data: {turbo_method: :post} %>
        <%# , data: { turbo_method: :create, turbo_confirm: 'This can take few seconds' } %>
      </div>
    </div>
  </div>
</div>